---
AllCops:
  Exclude:
  - vendor/**/*
  - "*/puppet/Puppetfile"
  - "*/puppet/.tmp/**/*"
  TargetRubyVersion: 2.2
  DisplayCopNames: true
Documentation:
  Enabled: false
AlignParameters:
  Enabled: true
BlockLength:
  Max: 50
HashSyntax:
  Enabled: true
LineLength:
  Enabled: false
EmptyLinesAroundBlockBody:
  Enabled: false
MethodLength:
  Max: 40
NumericLiterals:
  MinDigits: 10
Metrics/BlockLength:
  Max: 35
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 30
