---
AllCops:
  Exclude:
    - vendor/**/*
  TargetRubyVersion: 2.6
  DisplayCopNames: true
Layout/AlignParameters:
  Enabled: true
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Max: 50
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 40
Metrics/PerceivedComplexity:
  Max: 10
Style/Documentation:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/HashSyntax:
  Enabled: true
Style/NumericLiterals:
  MinDigits: 10
Style/NumericPredicate:
  Enabled: false
